code optimization to remove if and for
isaacs/minipass pull request #31
Opened 2022-01-29 09:24 UTC by MrJithil

2022-01-29 09:40 UTC, benjamingr commented on index.js
> +    const args = new Array(...arguments);
Nit: this can be:

```js
const args = [...arguments];
``

2022-02-26 22:25 UTC, isaacs requested changes
Go a bit further.

2022-02-26 22:25 UTC, isaacs commented on index.js
>        return super.emit.apply(this, args)
Can get rid of all of the above, I think, and just change this one line to:

```
return super.emit(...arguments)
```

That's what the `TODO` item was saying.  `arguments[0]` and `arguments[1]` are already ev and data, respectively.

2022-06-08 05:59 UTC, isaacs commented
Got swept up in some other perf enhancements on main.  Closing.  Thanks :)

2022-06-08 05:59 UTC, closed without merging